version: '2'
services:
  gitlab_14_9_4:
    image: 'gitlab/gitlab-ce:14.9.4-ce.0'
    restart: always
    hostname: ''www.testarea.com'
    container_name: gitlab_14_9_4
    environment:
      TZ:
        'Asia/Taipei'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://www.testarea.com'
        gitlab_rails['initial_root_password'] = 'initial_root_password'
        gitlab_rails['backup_archive_permissions'] = 0644
        gitlab_rails['backup_keep_time'] = 86400
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "email-smtp.ap-northeast-1.amazonaws.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "smtp_user_name"
        gitlab_rails['smtp_password'] = "smtp_password"
        gitlab_rails['smtp_domain'] = "testarea.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = 'admin@testarea.com'
        gitlab_rails['gitlab_email_reply_to'] = 'admin@testarea.com'
        gitlab_rails['time_zone'] = 'Asia/Taipei'
    ports:
      - '443:443'
      - '2224:22'
    volumes:
      - '${FOLDER}/config:/etc/gitlab'
      - '${FOLDER}/logs:/var/log/gitlab'
      - '${FOLDER}/data:/var/opt/gitlab'